### ISSUE TITLE
Не поддерживает Laravel 7

### ISSUE THREAD

**Issue by uzh13** [tochka-developers/jsonrpc#25]
Не устанавливается на 7 ларавель
При установке по readme пишет

  Problem 1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.0
    - Conclusion: remove laravel/framework v7.13.0
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.1|remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.1|don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.1|remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.1|don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.0|remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.0|don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Installation request for phpdocumentor/reflection-common (locked at 2.1.0) -> satisfiable by phpdocumentor/reflection-common[2.1.0].
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.0|remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install tochka-developers/jsonrpc v3.0.0|don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Installation request for phpdocumentor/reflection-docblock (locked at 5.1.0) -> satisfiable by phpdocumentor/reflection-docblock[5.1.0].
    - Conclusion: don't install laravel/framework v7.13.0
    - tochka-developers/jsonrpc v3.0.0-beta1 requires illuminate/container 5.7.*|5.8.*|^6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/container[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - tochka-developers/jsonrpc v3.0.0-beta2 requires illuminate/container 5.7.*|5.8.*|^6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/container[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - tochka-developers/jsonrpc v3.0.0-beta3 requires illuminate/container 5.7.*|5.8.*|^6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/container[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.13.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.13.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.13.0].
    - don't install illuminate/container 5.7.17|don't install laravel/framework v7.13.0
    - don't install illuminate/container 5.7.18|don't install laravel/framework v7.13.0
    - don't install illuminate/container 5.7.19|don't install laravel/framework v7.13.0
    - don't install illuminate/container 5.7.x-dev|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.10|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.11|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.15|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.2|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.20|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.21|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.22|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.23|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.26|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.27|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.28|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.3|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.4|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.5|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.6|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.7|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.8|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.7.9|don't install laravel/framework v7.13.0
    - don't install illuminate/container 5.8.x-dev|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.11|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.12|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.14|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.15|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.17|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.18|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.19|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.2|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.20|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.22|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.24|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.27|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.28|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.29|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.3|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.30|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.31|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.32|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.33|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.34|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.35|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.36|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.4|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.8|don't install laravel/framework v7.13.0
    - don't install illuminate/container v5.8.9|don't install laravel/framework v7.13.0
    - don't install illuminate/container 6.x-dev|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.0.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.0.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.0.2|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.0.3|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.0.4|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.1.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.10.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.11.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.12.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.13.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.13.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.14.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.15.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.15.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.16.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.17.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.17.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.10|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.11|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.12|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.13|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.14|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.15|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.16|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.17|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.18|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.2|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.3|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.4|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.5|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.6|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.7|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.8|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.18.9|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.2.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.3.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.4.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.5.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.5.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.5.2|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.6.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.6.1|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.6.2|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.7.0|don't install laravel/framework v7.13.0
    - don't install illuminate/container v6.8.0|don't install laravel/framework v7.13.0
    - Installation request for laravel/framework (locked at v7.13.0, required as ^7.0) -> satisfiable by laravel/framework[v7.13.0].
    - Installation request for tochka-developers/jsonrpc ^3.0 -> satisfiable by tochka-developers/jsonrpc[v3.0.0, v3.0.0-beta1, v3.0.0-beta2, v3.0.0-beta3, v3.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by XandrKhv** [comment]
composer require tochka-developers/jsonrpc:"^3.0.1"
Единственное в пакете старая версия  phpdocumentor/reflection-docblock, 4.3, а надо бы уже 5.1

**Comment by darkdarin** [comment]
Убрал конфликтующий пакет + обновил документацию. Теперь должно установиться без проблем.
